# Generators.py
# Low-level instruction generator definitions.
#
# "base_cost"  : cost of the FIRST purchase; each subsequent purchase
#                costs base_cost * 1.15^owned (cookie-clicker style scaling).
# "increment"  : base instructions/sec contributed per owned unit
#                (before any multipliers are applied).
#
# Costs are tuned so that, playing normally, each new generator tier takes
# roughly 300 seconds of current income to afford the first copy.

GENERATORS = [
    {
        "name": "MOV",
        "label": "Buy MOV Unit",
        "base_cost": 10,
        "increment": 1,
        "info": (
            "MOV — Move / Register Copy\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Copies a value from one register to another.\n"
            "  No arithmetic is performed — pure data transfer.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 (AArch64)\n"
            "──────────────────────────────────────────\n"
            "  mov x0, x1\n\n"
            "  • ARM64 has NO dedicated MOV opcode for reg-to-reg.\n"
            "  • The assembler rewrites it as:  ORR x0, xzr, x1\n"
            "    (OR the source with the zero register XZR → x0)\n"
            "  • XZR is a hard-wired zero register — reads always return\n"
            "    0, writes are silently discarded. ARM uses it everywhere\n"
            "    to avoid needing separate 'clear' or 'copy' opcodes.\n"
            "  • Immediate form:  mov x0, #42  (encoded as MOVZ)\n\n"
            "──────────────────────────────────────────\n"
            "x86-64\n"
            "──────────────────────────────────────────\n"
            "  mov rax, rbx\n\n"
            "  • x86-64 HAS a real MOV opcode — one of its most-used.\n"
            "  • MOV is heavily overloaded: it handles reg→reg, mem→reg,\n"
            "    reg→mem, and imm→reg all under the same mnemonic.\n"
            "  • No zero register. Clearing uses:  xor rax, rax\n"
            "    (faster than  mov rax, 0  — no immediate to decode).\n\n"
            "══════════════════════════════════════════\n"
            "KEY DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64 : MOV is a pseudo-instruction — an assembler alias\n"
            "          for ORR with XZR. Not a real opcode.\n"
            "  x86-64: MOV is a real, dedicated opcode in the ISA.\n\n"
            "  ARM's RISC philosophy: fewer real opcodes, more aliases,\n"
            "  keeping the hardware decoder simple and fast."
        ),
    },
    {
        "name": "ADD",
        "label": "Buy ADD Unit",
        "base_cost": 100,
        "increment": 5,
        "info": (
            "ADD — Integer Addition\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Adds two values and stores the result. Used in arithmetic,\n"
            "  array indexing, pointer math, and loop counters.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 (AArch64)\n"
            "──────────────────────────────────────────\n"
            "  add  x0, x1, x2      ; x0 = x1 + x2\n"
            "  add  x0, x1, #10     ; x0 = x1 + 10  (immediate)\n"
            "  adds x0, x1, x2      ; same, AND sets NZCV flags\n"
            "  add  x0, x1, x2, lsl #2  ; x0 = x1 + (x2 << 2)\n"
            "                            ;    = x1 + x2*4\n\n"
            "  • THREE operands: destination is always separate.\n"
            "    Source registers are NEVER overwritten (non-destructive).\n"
            "  • The 'S' suffix (ADDS) opts IN to flag-setting.\n"
            "    Without it, flags are untouched — great when you want\n"
            "    to add without clobbering a pending comparison result.\n"
            "  • Shifted-register form lets you scale an index in one\n"
            "    instruction. add x0, x1, x2, lsl #2 is equivalent to\n"
            "    an array dereference:  x0 = base + index * 4.\n\n"
            "──────────────────────────────────────────\n"
            "x86-64\n"
            "──────────────────────────────────────────\n"
            "  add  rax, rbx        ; rax = rax + rbx  (rbx unchanged)\n"
            "  add  rax, 10         ; rax = rax + 10\n"
            "  lea  rax, [rbx+rcx*4]; rax = rbx + rcx*4  (scaled index)\n\n"
            "  • TWO operands: destination is ALSO the first source.\n"
            "    The left operand is ALWAYS overwritten.\n"
            "  • ALWAYS sets flags (CF, ZF, SF, OF, PF) — no opt-out.\n"
            "  • No built-in shift in ADD. LEA (Load Effective Address)\n"
            "    is the workaround for scaled indexing — it computes an\n"
            "    address expression without actually accessing memory.\n\n"
            "══════════════════════════════════════════\n"
            "KEY DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64 : 3 operands, non-destructive, opt-in flag setting,\n"
            "          built-in shift for scaled addressing.\n"
            "  x86-64: 2 operands, destructive, always sets flags,\n"
            "          uses LEA as a workaround for scaled addressing.\n\n"
            "  ARM's 3-operand form is a major ergonomic advantage —\n"
            "  compilers can reuse source registers freely without\n"
            "  spilling them to the stack."
        ),
    },
    {
        "name": "IF_INST",
        "label": "Buy IF Unit",
        "base_cost": 500,
        "increment": 20,
        "info": (
            "Conditional Branch\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Jump to a different code location based on the result of\n"
            "  a previous comparison. This is the compiled form of\n"
            "  if / else logic.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 (AArch64)\n"
            "──────────────────────────────────────────\n"
            "  cmp  x0, x1          ; subtract x0-x1, set NZCV flags\n"
            "  b.eq label           ; branch if Equal        (Z=1)\n"
            "  b.ne label           ; branch if Not Equal    (Z=0)\n"
            "  b.lt label           ; branch if Less Than    (signed)\n"
            "  b.gt label           ; branch if Greater Than (signed)\n"
            "  b.lo label           ; branch if Lower        (unsigned)\n"
            "  b.hi label           ; branch if Higher       (unsigned)\n\n"
            "  ; Shortcut: compare-and-branch without a CMP:\n"
            "  cbz  x0, label       ; branch if x0 == 0\n"
            "  cbnz x0, label       ; branch if x0 != 0\n\n"
            "  • Condition is a SUFFIX on a single B opcode (B.cond).\n"
            "  • NZCV = Negative, Zero, Carry, oVerflow — 4 bits in\n"
            "    PSTATE (the processor state register).\n"
            "  • CBZ/CBNZ can skip the CMP entirely for zero-checks —\n"
            "    saves an instruction in the very common  if (x == 0).\n\n"
            "──────────────────────────────────────────\n"
            "x86-64\n"
            "──────────────────────────────────────────\n"
            "  cmp  rax, rbx        ; subtract rax-rbx, set EFLAGS\n"
            "  je   label           ; jump if Equal\n"
            "  jne  label           ; jump if Not Equal\n"
            "  jl   label           ; jump if Less    (signed)\n"
            "  jg   label           ; jump if Greater (signed)\n"
            "  jb   label           ; jump if Below   (unsigned)\n"
            "  ja   label           ; jump if Above   (unsigned)\n\n"
            "  ; Common zero-check idiom (no shortcut opcode):\n"
            "  test rax, rax        ; rax & rax → sets ZF if zero\n"
            "  jz   label           ; jump if Zero\n\n"
            "  • Each condition is a SEPARATE opcode (je, jne, jl …).\n"
            "  • EFLAGS: CF (Carry), ZF (Zero), SF (Sign), OF (Overflow),\n"
            "    PF (Parity). More bits than ARM's NZCV.\n"
            "  • No combined compare-and-branch — always two instructions.\n\n"
            "══════════════════════════════════════════\n"
            "KEY DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64 : ONE branch opcode family with a condition suffix.\n"
            "          CBZ/CBNZ eliminate the CMP for zero comparisons.\n"
            "  x86-64: Each condition is a distinct opcode (je, jne …).\n"
            "          More mnemonics to learn; no shortcut for zero-checks.\n\n"
            "  In practice the compiled output looks very similar, but\n"
            "  ARM's CBZ shortcut is a notable code-density win."
        ),
    },
    {
        "name": "LOAD_STORE",
        "label": "Buy LOAD/STORE Unit",
        "base_cost": 2_000,
        "increment": 80,
        "info": (
            "LOAD / STORE — Memory Access\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Move data between CPU registers and main memory (RAM).\n"
            "  Registers hold what the CPU works on right now;\n"
            "  memory holds everything else.  LOAD brings data in;\n"
            "  STORE writes data out.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 — RISC: dedicated LOAD/STORE opcodes only\n"
            "──────────────────────────────────────────\n"
            "  ldr  x0, [x1]        ; load  64-bit at address x1 → x0\n"
            "  ldr  w0, [x1]        ; load  32-bit (zero-extends to 64)\n"
            "  ldrb w0, [x1]        ; load   8-bit byte\n"
            "  ldrh w0, [x1]        ; load  16-bit halfword\n"
            "  ldrsb x0, [x1]       ; load   8-bit, sign-extend to 64\n"
            "  str  x0, [x1]        ; store 64-bit x0 → address x1\n\n"
            "  ; Addressing modes:\n"
            "  ldr  x0, [x1, #8]    ; offset:     load from x1+8\n"
            "  ldr  x0, [x1, #8]!   ; pre-index:  x1 += 8, then load\n"
            "  ldr  x0, [x1], #8    ; post-index: load, then x1 += 8\n\n"
            "  ; Pair instructions (two registers at once):\n"
            "  ldp  x0, x1, [sp]          ; load  x0 and x1 from stack\n"
            "  stp  x29, x30, [sp, #-16]! ; push  frame ptr & link reg\n\n"
            "  • ONLY LDR/STR can access memory. Arithmetic MUST use\n"
            "    registers. This is the core RISC contract.\n"
            "  • LDP/STP push/pop two registers in a single instruction.\n\n"
            "──────────────────────────────────────────\n"
            "x86-64 — CISC: MOV does load, store, AND more\n"
            "──────────────────────────────────────────\n"
            "  mov  rax, [rbx]      ; load  64-bit from address rbx\n"
            "  mov  eax, [rbx]      ; load  32-bit (zero-extends)\n"
            "  movsx rax, byte [rbx]; load   8-bit, sign-extend to 64\n"
            "  mov  [rbx], rax      ; store 64-bit rax → address rbx\n"
            "  mov  [rbx+8], rax    ; store to  rbx + 8\n\n"
            "  ; CISC bonus: memory operands in arithmetic directly:\n"
            "  add  rax, [rbx]      ; rax += *(rbx)  — no load needed!\n"
            "  ; ARM would need:  ldr x1,[x1]  then  add x0,x0,x1\n\n"
            "══════════════════════════════════════════\n"
            "KEY DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64 (RISC): LDR/STR are ONLY memory opcodes. All math\n"
            "    must be in registers first. More instructions total, but\n"
            "    each is simple and easy for the CPU to pipeline.\n"
            "  x86-64 (CISC): MOV handles load AND store. Arithmetic\n"
            "    instructions can take memory operands directly — fewer\n"
            "    instructions, but each can be much more complex.\n\n"
            "  ARM's LDP/STP is a key efficiency win — x86 needs two\n"
            "  separate PUSH/POP instructions to do the same thing."
        ),
    },
    {
        "name": "CMP",
        "label": "Buy CMP Unit",
        "base_cost": 8_000,
        "increment": 300,
        "info": (
            "CMP — Compare\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Subtracts two values and DISCARDS the result — keeping\n"
            "  only the CPU flags it sets. Those flags are then read by\n"
            "  a following conditional branch to make a decision.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 (AArch64)\n"
            "──────────────────────────────────────────\n"
            "  cmp  x0, x1          ; compute x0 - x1, set NZCV\n"
            "  cmp  x0, #100        ; compare register with immediate\n"
            "  cmn  x0, x1          ; Compare Negative: x0 + x1 → flags\n"
            "                       ; (compares x0 against -x1)\n"
            "  tst  x0, x1          ; Test: x0 AND x1 → flags (NZ only)\n"
            "                       ; checks if specific bits are set\n\n"
            "  • CMP is an alias for:  SUBS xzr, x0, x1\n"
            "    (Subtract with flags, store result in XZR = discard).\n"
            "  • NZCV flags:\n"
            "      N = Negative   (result < 0)\n"
            "      Z = Zero       (result == 0)\n"
            "      C = Carry      (unsigned borrow/overflow)\n"
            "      V = oVerflow   (signed overflow)\n"
            "  • TST is the bit-mask companion (alias for ANDS xzr, ...).\n"
            "    Used to check:  if (x & mask) ...  without full AND.\n\n"
            "──────────────────────────────────────────\n"
            "x86-64\n"
            "──────────────────────────────────────────\n"
            "  cmp  rax, rbx        ; compute rax - rbx, set EFLAGS\n"
            "  cmp  rax, 100        ; compare with immediate\n"
            "  test rax, rbx        ; rax AND rbx → flags (ZF, SF, PF)\n"
            "  test rax, rax        ; canonical: check if rax == 0\n\n"
            "  • CMP is a real, dedicated opcode — not a pseudo.\n"
            "  • EFLAGS set: CF (Carry), ZF (Zero), SF (Sign),\n"
            "    OF (Overflow), PF (Parity), AF (Auxiliary Carry).\n"
            "  • TEST rax, rax is THE canonical zero-check idiom.\n"
            "    Faster than  cmp rax, 0  — no immediate to decode.\n"
            "    Compilers almost always emit TEST instead of CMP #0.\n\n"
            "══════════════════════════════════════════\n"
            "KEY DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  Both use subtract-and-discard — same logical concept.\n\n"
            "  ARM64 : CMP is a pseudo-instruction (SUBS + XZR).\n"
            "          4 flag bits in PSTATE (NZCV).\n"
            "  x86-64: CMP is a real opcode.\n"
            "          6 relevant bits in the 32-bit EFLAGS register.\n\n"
            "  The extra PF and AF bits in EFLAGS are legacy x86 baggage\n"
            "  rarely used in modern code — ARM's cleaner 4-bit NZCV\n"
            "  reflects its younger, cleaner design."
        ),
    },
    {
        "name": "BRANCH",
        "label": "Buy BRANCH Unit",
        "base_cost": 30_000,
        "increment": 1_000,
        "info": (
            "BRANCH — Unconditional & Conditional Jump\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Change the Program Counter (PC) to a new address.\n"
            "  Unconditional: always jumps. Conditional: jumps only if\n"
            "  flags from a prior CMP/TEST match the condition.\n"
            "  Branches implement loops, if/else, and function calls.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 (AArch64)\n"
            "──────────────────────────────────────────\n"
            "  ; Unconditional:\n"
            "  b    label           ; branch to label (PC-relative)\n"
            "  br   x0              ; branch to address in register x0\n\n"
            "  ; Conditional (after a CMP):\n"
            "  b.eq label           ; branch if Equal\n"
            "  b.ne label           ; branch if Not Equal\n"
            "  b.lt label           ; branch if Less Than   (signed)\n"
            "  b.ge label           ; branch if ≥            (signed)\n"
            "  b.lo label           ; branch if Lower        (unsigned)\n"
            "  b.cs label           ; branch if Carry Set\n\n"
            "  ; Compare-and-branch (no CMP needed):\n"
            "  cbz  x0, label       ; branch if x0 == 0\n"
            "  cbnz x0, label       ; branch if x0 != 0\n"
            "  tbz  x0, #3, label   ; branch if bit 3 of x0 is 0\n"
            "  tbnz x0, #3, label   ; branch if bit 3 of x0 is 1\n\n"
            "  • All ARM64 branches are PC-relative (position-independent).\n"
            "  • B range: ±128 MB. BL (branch with link / call): ±128 MB.\n"
            "  • CBZ/CBNZ/TBZ/TBNZ eliminate a CMP in common patterns.\n\n"
            "──────────────────────────────────────────\n"
            "x86-64\n"
            "──────────────────────────────────────────\n"
            "  ; Unconditional:\n"
            "  jmp  label           ; jump to label\n"
            "  jmp  rax             ; jump to address in register\n\n"
            "  ; Conditional (each condition = its own opcode):\n"
            "  je   label           ; jump if Equal        (ZF=1)\n"
            "  jne  label           ; jump if Not Equal    (ZF=0)\n"
            "  jl   label           ; jump if Less         (SF≠OF)\n"
            "  jge  label           ; jump if ≥\n"
            "  jb   label           ; jump if Below        (unsigned)\n"
            "  ja   label           ; jump if Above        (unsigned)\n"
            "  jrcxz label          ; jump if RCX == 0  (loop counter)\n\n"
            "  • Near jumps: ±2 GB range (32-bit displacement).\n"
            "  • No combined compare-and-branch shortcut — always 2 instr.\n\n"
            "══════════════════════════════════════════\n"
            "KEY DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64 : ONE B opcode with a condition suffix (B.cond).\n"
            "          CBZ/CBNZ/TBZ eliminate a CMP in many loop patterns.\n"
            "          Fewer unique mnemonics to learn.\n"
            "  x86-64: Every condition is its own opcode (je, jne, jl …).\n"
            "          More mnemonics; no shortcut for zero/bit checks.\n\n"
            "  ARM's shorter encoding and CBZ shortcuts mean tighter loops\n"
            "  and better instruction-cache utilization — real performance\n"
            "  gains in tight inner loops."
        ),
    },
]